### ISSUE TITLE
[Android] connect function crashes

### ISSUE THREAD

**Issue by egodefroy** [WinkMeter/flutter_socket_io#18]
Connect function crashes on Android, not on iOS

````
E/EventThread(20050): Task threw exception
E/EventThread(20050): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: EventThread
E/EventThread(20050): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/EventThread(20050): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/EventThread(20050): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/EventThread(20050): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
E/EventThread(20050): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/EventThread(20050): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/EventThread(20050): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/EventThread(20050): 	at com.itsclicking.clickapp.fluttersocketio.SocketIO.onSocketCallback(SocketIO.java:121)
E/EventThread(20050): 	at com.itsclicking.clickapp.fluttersocketio.SocketIO.access$000(SocketIO.java:28)
E/EventThread(20050): 	at com.itsclicking.clickapp.fluttersocketio.SocketIO$9.call(SocketIO.java:144)
E/EventThread(20050): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/EventThread(20050): 	at io.socket.client.Socket.access$601(Socket.java:24)
E/EventThread(20050): 	at io.socket.client.Socket$5.run(Socket.java:186)
E/EventThread(20050): 	at io.socket.thread.EventThread.exec(EventThread.java:55)
E/EventThread(20050): 	at io.socket.client.Socket.emit(Socket.java:182)
E/EventThread(20050): 	at io.socket.client.Socket.onconnect(Socket.java:389)
E/EventThread(20050): 	at io.socket.client.Socket.onpacket(Socket.java:283)
E/EventThread(20050): 	at io.socket.client.Socket.access$100(Socket.java:24)
E/EventThread(20050): 	at io.socket.client.Socket$2$2.call(Socket.java:120)
E/EventThread(20050): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/EventThread(20050): 	at io.socket.client.Manager.ondecoded(Manager.java:427)
E/EventThread(20050): 	at io.socket.client.Manager.access$1600(Manager.java:30)
E/EventThread(20050): 	at io.socket.client.Manager$7.call(Manager.java:403)
E/EventThread(20050): 	at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
E/EventThread(20050): 	at io.socket.client.Manager.ondata(Manager.java:419)
E/EventThread(20050): 	at io.socket.client.Manager.access$1000(Manager.java:30)
E/EventThread(20050): 	at io.socket.client.Manager$2.call(Manager.java:370)
E/EventThread(20050): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/EventThread(20050): 	at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
E/EventThread(20050): 	at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
E/EventThread(20050): 	at io.socket.engineio.client.Socket$5.call(Socket.java:335)
E/EventThread(20050): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/EventThread(20050): 	at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
E/EventThread(20050): 	at io.socket.engineio.client.Transport.onData(Transport.java:118)
E/EventThread(20050): 	at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
E/EventThread(20050): 	at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
E/EventThread(20050): 	at io.socket.thread.EventThread$2.run(EventThread.java:80)
E/EventThread(20050): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/EventThread(20050): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/EventThread(20050): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(20050): FATAL EXCEPTION: EventThread
E/AndroidRuntime(20050): Process: com.egylis.moveon.formation, PID: 20050
E/AndroidRuntime(20050): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: EventThread
E/AndroidRuntime(20050): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime(20050): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/AndroidRuntime(20050): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/AndroidRuntime(20050): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
E/AndroidRuntime(20050): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/AndroidRuntime(20050): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime(20050): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime(20050): 	at com.itsclicking.clickapp.fluttersocketio.SocketIO.onSocketCallback(SocketIO.java:121)
E/AndroidRuntime(20050): 	at com.itsclicking.clickapp.fluttersocketio.SocketIO.access$000(SocketIO.java:28)
E/AndroidRuntime(20050): 	at com.itsclicking.clickapp.fluttersocketio.SocketIO$9.call(SocketIO.java:144)
E/AndroidRuntime(20050): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(20050): 	at io.socket.client.Socket.access$601(Socket.java:24)
E/AndroidRuntime(20050): 	at io.socket.client.Socket$5.run(Socket.java:186)
E/AndroidRuntime(20050): 	at io.socket.thread.EventThread.exec(EventThread.java:55)
E/AndroidRuntime(20050): 	at io.socket.client.Socket.emit(Socket.java:182)
E/AndroidRuntime(20050): 	at io.socket.client.Socket.onconnect(Socket.java:389)
E/AndroidRuntime(20050): 	at io.socket.client.Socket.onpacket(Socket.java:283)
E/AndroidRuntime(20050): 	at io.socket.client.Socket.access$100(Socket.java:24)
E/AndroidRuntime(20050): 	at io.socket.client.Socket$2$2.call(Socket.java:120)
E/AndroidRuntime(20050): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(20050): 	at io.socket.client.Manager.ondecoded(Manager.java:427)
E/AndroidRuntime(20050): 	at io.socket.client.Manager.access$1600(Manager.java:30)
E/AndroidRuntime(20050): 	at io.socket.client.Manager$7.call(Manager.java:403)
E/AndroidRuntime(20050): 	at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
E/AndroidRuntime(20050): 	at io.socket.client.Manager.ondata(Manager.java:419)
E/AndroidRuntime(20050): 	at io.socket.client.Manager.access$1000(Manager.java:30)
E/AndroidRuntime(20050): 	at io.socket.client.Manager$2.call(Manager.java:370)
E/AndroidRuntime(20050): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(20050): 	at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
E/AndroidRuntime(20050): 	at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
E/AndroidRuntime(20050): 	at io.socket.engineio.client.Socket$5.call(Socket.java:335)
E/AndroidRuntime(20050): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(20050): 	at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
E/AndroidRuntime(20050): 	at io.socket.engineio.client.Transport.onData(Transport.java:118)
E/AndroidRuntime(20050): 	at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
E/AndroidRuntime(20050): 	at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
E/AndroidRuntime(20050): 	at io.socket.thread.EventThread$2.run(EventThread.java:80)
E/AndroidRuntime(20050): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(20050): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(20050): 	at java.lang.Thread.run(Thread.java:764)
````

````
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.6.1-pre.32, on Mac OS X 10.13.6 17G7024, locale
    fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (3 available)

• No issues found!
````

**Comment by mkrishnappa** [comment]
@egodefroy were you able to get this plugin work on iOS? because when I tried, I ran into this issue.. https://github.com/WinkMeter/flutter_socket_io/issues/17

**Comment by egodefroy** [comment]
@mkrishnappa so far I didn't have any problem on iOS in this environment and flutter version as well as with the previous ones.

Are you on a more recent version ?

**Comment by mkrishnappa** [comment]
@egodefroy yes, I am on the latest version. My experience with iOS environment and swift / objective-c programming language is very limited and there is a good chance that I might be missing something when I set it up. 
I have followed the steps provided on the plugin page for iOS.
1. Copy the folder example/ios/Runner/SocketObj to ${PROJECT_ROOT}/ios/Runner/
2. Replace the ${PROJECT_ROOT}/ios/Runner/AppDelegate.m with example/ios/Runner/AppDelegate.m. (Notice: You should merge the old one in your project to merge with the new from this plugin if you have some change on that file)
3. Open ${PROJECT_ROOT}/ios/Podfile, paste this line pod 'Socket.IO-Client-Swift', '~> 13.3.0' before the end of target 'Runner' do block

at the end I ran into this issue https://github.com/WinkMeter/flutter_socket_io/issues/17 

when you created the flutter project, did you provide swift support to the project [flutter create -i swift project_name] or was it just [flutter create project_name] ? 
I have created my project using this command [flutter create -i swift project_name] 

Any input / help will be very helpful. 
Thank you!

**Comment by thekeels** [comment]
Using flutter 1.9.1+hotfix.5 --> I am working through exercises in the Practical Flutter book by Zammetti, and it uses this package. It does not work for either Android or iOS. Android it gets the error seen by @egodefroy , and on iOS it get the error seen by @mkrishnappa . The source code used for that is chapter 7/8 https://github.com/Apress/practical-flutter/tree/master/ch_07%2B08/flutter_chat
