### ISSUE TITLE
cannot working on IOS

### ISSUE THREAD

**Issue by vohoangtuit** [WinkMeter/flutter_socket_io#57]
for me, on android working, but ios not working, when me start socket and receive with error: 

[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method socketInit on channel flutter_socket_io)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      SocketIO.init (package:flutter_socket_io/flutter_socket_io.dart:70:5)

**Comment by shashoug** [comment]
Please make sure you run `pod deintegrate` then run `pod install` and you good to try it out

**Comment by venkateshavenki** [comment]
> Please make sure you run `pod deintegrate` then run `pod install` and you good to try it out

I tried the above command but it is not working.

**Comment by Jkarthikeyan003** [comment]
I tried the above command but it is not working.

**Comment by Jkarthikeyan003** [comment]
> Please make sure you run `pod deintegrate` then run `pod install` and you good to try it out

I tried the above command but it is not working.
