### ISSUE TITLE
Error output from Xcode build:

### ISSUE THREAD

**Issue by jcarvalhogo** [WinkMeter/flutter_socket_io#6]
Launching lib/main.dart on iPhone 5s in debug mode...
Starting Xcode build...
Xcode build done.                                            1,2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by jcarvalhogo** [comment]
Launching lib/main.dart on iPhone 6s in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - Socket.IO-Client-Swift
      - flutter_socket_io

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_socket_io` from `.symlinks/plugins/flutter_socket_io/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A Socket.IO-Client-Swift
      A Starscream
      A flutter_socket_io

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing Socket.IO-Client-Swift (13.3.0)
      > Copying Socket.IO-Client-Swift from `/Users/jcarvalho/Library/Caches/CocoaPods/Pods/Release/Socket.IO-Client-Swift/13.3.0-0afb1` to `Pods/Socket.IO-Client-Swift`

    -> Installing Starscream (3.0.5)
      > Copying Starscream from `/Users/jcarvalho/Library/Caches/CocoaPods/Pods/Release/Starscream/3.0.5-faf91` to `Pods/Starscream`

    -> Installing flutter_socket_io (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `Socket.IO-Client-Swift` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    - `Starscream` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/target_validator.rb:115:in `verify_swift_pods_swift_version'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 6s.

**Comment by jcarvalhogo** [comment]
Launching lib/main.dart on iPhone 6s in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - Socket.IO-Client-Swift
      - flutter_socket_io

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_socket_io` from `.symlinks/plugins/flutter_socket_io/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A Socket.IO-Client-Swift
      A Starscream
      A flutter_socket_io

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing Socket.IO-Client-Swift (13.3.0)
      > Copying Socket.IO-Client-Swift from `/Users/jcarvalho/Library/Caches/CocoaPods/Pods/Release/Socket.IO-Client-Swift/13.3.0-0afb1` to `Pods/Socket.IO-Client-Swift`

    -> Installing Starscream (3.0.5)
      > Copying Starscream from `/Users/jcarvalho/Library/Caches/CocoaPods/Pods/Release/Starscream/3.0.5-faf91` to `Pods/Starscream`

    -> Installing flutter_socket_io (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `Socket.IO-Client-Swift` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    - `Starscream` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/target_validator.rb:115:in `verify_swift_pods_swift_version'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 6s.

**Comment by markqq** [comment]
Creating an empty swift file in the project by Xcode could solve the problem.
